### ISSUE TITLE
Comparison of fitting transit with and without GP

### ISSUE THREAD

**Issue by ericagol** [dfm/araa-gps#18]
In Figure 3, it seems clear that the orange fit in the left panel is very poor - many of the error bars
are 2-3 sigma away from the model.  I'm wondering if a fairer comparison would be one in which
the error bars are inflated (which has been common practice in exoplanet work), or detrending
with a polynomial (also a common practice)?  Otherwise the large chi-square causes a narrow
posterior for this fit, I think, while I would expect that the discrepancy with the correct values should 
still remain.

https://github.com/dfm/araa-gps/blob/a659c2ccdcbd30bacf6bb52e845f071ebae08a1f/src/tex/ms.tex#L219-L226

**Comment by dfm** [comment]
Good point - I've added a jitter term to both models and it increases the uncertainties on the independent noise fit, but the results are still significantly inconsistent as expected. It might also be worth adding some words about model checking, but I've just left a note in the draft that we can revisit as necessary. (we're already in trouble because of page limits...)
