### ISSUE TITLE
Scientific editor 1 comments

### ISSUE THREAD

**Issue by saigrain** [dfm/araa-gps#37]
- [x] Figure 4 caption repeats "thick":  thick thick  
- [x] Section 3.1 the first sentences says "scakar" and this should be "scalar" 
- [x]  Section 3.1.1. the word "the" is repeated: the the
- [x] The opening examples in Section 1.2 both rely on MCMC. The ability to couple GPR with a probabilistic framework for parameter estimation is a key point that, while discussed in Section 3.2, could be mentioned in the opening statements as one of the reasons for GPR’s increasing adoption.
- [x] Figure 4: "Gaussian Field” is a relatively technical term for the intended audience, and it is not defined in the article. Consider changing, or adding a definition.
- [x] Stylistically, consider expanding contraction language e.g. changing “aren’t" to "are not."
- [x] Section 3.2: the authors state that MCMC + NUTS were used for all examples. This was already stated in the opening paragraphs with nearly identical language.
- [x] Page 19: “drop-in replacement.” GPR is particularly useful for modeling correlated structure in data, and definitely could be a useful tool in otherwise standard chi-square analyses. However, many situations are straightforward: independent samples drawn from an underlying physical model plus white noise. In this case, the extra parameters introduced by a common GP model (e.g. exponential kernels) are unnecessary and not physically motivated. Add language to the effect: “where there may be correlated noise."

**Comment by dfm** [comment]
Thanks @saigrain!

> I could remove the repeated text in Section 3.2, or do you think we should leave it?

I'm happy for us to cut it!

> I would be tempted to push back on this because I've yet to come across a dataset where I could safely say there's no correlated noise before analysing it... What's your view?

I'm totally with you! We could comment that there may be cases where a model of the correlated noise is not required to adequately model the data but, since the independent noise model is a special case of most GP models, using a GP isn't conceptually problematic - especially when you use the model assessment tools discussed here. There may be computational reasons or non-Gaussianity that could cause you to avoid using a GP, but we also discuss that.
